Feature/seext 10469 extend drop downs nav bar style name to have background color of navbar
shoutem/ui pull request #640
Opened 2021-09-20 17:47 UTC by tomislav-arambasic

We were using horizontal styleName for categories `DropDown` component, in our CMS extensions.
That styleName didn't meet the requirements of new feature design - CMS search.

I've extended current `navBar` style to have background color of the navbar.

Before, with `horizontal` styleName:
![Screenshot 2021-09-20 at 19 43 21](https://user-images.githubusercontent.com/57353746/134049557-bdfd1433-ae0a-4679-9121-4466c4605e16.png)

After, with new `navBar`
![Screenshot 2021-09-20 at 19 43 47](https://user-images.githubusercontent.com/57353746/134049565-434cd60e-1489-4b0a-81d2-9068239b96b0.png)
:

2021-09-21 07:28 UTC, majaklajic approved these changes
It looks good to me, but be sure to test all layout combinations...

2021-09-21 07:54 UTC, ltatarev approved these changes

2021-09-21 10:09 UTC, toroz approved these changes

2021-09-21 12:22 UTC, sstimac requested changes
Discussed in person with Tomislav. We need to make some other changes here

2021-09-22 15:25 UTC, tomislav-arambasic commented
@sstimac @toroz 

Changed per request.
I've updated PR description & added screenshots showing default dropdown UI per theme & dropdown UI for Prime theme, after changing new dropdown theme theme properties - bg & text colors.

2021-09-23 06:49 UTC, tomislav-arambasic commented
Closing this, as I've opened a new PR (had to change name of the task).
New PR -> https://github.com/shoutem/ui/pull/641

2021-09-23 06:49 UTC, closed without merging