Feature/make scroll driver updateable
shoutem/ui pull request #671
Opened 2022-01-13 11:38 UTC by Definitely-Not-Vlad

- adds `onAnimationDriverChange` handler which allows us to update things outside of the `ScrollView` when the animation driver changes

2022-01-14 12:15 UTC, sstimac requested changes

2022-01-14 12:15 UTC, sstimac commented on components/ScrollView/ScrollDriverProvider.js
> +    onAnimationDriverChange: PropTypes.func,
let's document this prop and explain why we're using it. ( We need this prop to propagate the driver change to recalculate navigational styles. We won't have the need for this prop once we rewrite using the new Context API )

2022-01-14 13:45 UTC, Definitely-Not-Vlad commented on components/ScrollView/ScrollView.js
> +    const { animationDriver, driverProvider } = this.context;
`ScrollDriverProvider` is the one that handles `primary` prop change`, `ScrollView`'s `componentDidUpdate` just had excess code removed.

As is, this works as intended.

2022-01-17 10:54 UTC, sstimac approved these changes

2022-01-17 10:54 UTC, merged